# Generated by Django 3.2.9 on 2021-12-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211120_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.IntegerField(default=560000, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
