# Generated by Django 3.2.9 on 2021-12-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
