# Generated by Django 3.2.9 on 2021-12-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211205_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
